name: Python and R Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      r:
        image: rocker/r-ver:4.1.2
        ports:
          - 6311:6311
        options: --name=r-service

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install R Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        sudo apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev  
        Rscript -e "try(install.packages(c('R6', 'Rcpp', 'skimr'), lib='.', dependencies=TRUE, repos='https://cloud.r-project.org'), silent=FALSE)"        
        Rscript -e 'try(utils::install.packages("learningmachine", repos="https://techtonique.r-universe.dev", dependencies = TRUE, lib="."), silent=FALSE)'

    - name: Install Python Dependencies
      run: |     
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip       
        python -m pip list
        python -m pip install rpy2
        python -m pip install -r requirements.txt
        python -m pip install .

    - name: Debug Info
      run: |
        python --version
        python -m pip list
        Rscript --version
    
    - name: Run Python Examples from Subdirectory
      run: |
        find examples -maxdepth 2 -name "*.py" -exec  python {} \;