name: Python and R Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      r:
        image: rocker/r-ver:4.1.2
        ports:
          - 6311:6311
        options: --name=r-service

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install R Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        sudo apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev
        Rscript -e 'install.packages(c('cli','cpp11','digest','dplyr','ellipsis','evaluate','fansi','fastmap','generics','glue','highr','htmltools','jsonlite','knitr','lifecycle','magrittr','pillar','pkgconfig','purrr','R6','Rcpp','remotes','repr','rlang','skimr','stringi','stringr','tibble','tidyr','tidyselect','utf8','vctrs','withr','xfun','yaml','base','boot','class','cluster','codetools','compiler','datasets','foreign','graphics','grDevices','grid','KernSmooth','lattice','MASS','Matrix','methods','mgcv','nlme','nnet','parallel','rpart','spatial','splines','stats','stats4','survival','tcltk','tools','utils'), repos="https://cloud.r-project.org")'
        Rscript -e 'try(utils::install.packages("learningmachine", repos="https://techtonique.r-universe.dev", dependencies = TRUE), silent=TRUE)'
        Rscript -e 'utils::install.packages("learningmachine", repos="https://techtonique.r-universe.dev", dependencies = TRUE, lib=".")'

    - name: Install Python Dependencies
      run: |     
        python -m ensurepip --default-pip
        python -m pip install --upgrade pip       
        python -m pip list
        python -m pip install rpy2
        python -m pip install -r requirements.txt
        python -m pip install .

    - name: Debug Info
      run: |
        python --version
        python -m pip list
        Rscript --version
    
    - name: Run Python Examples from Subdirectory
      run: |
        find examples -maxdepth 2 -name "*.py" -exec  python {} \;