name: Python and R Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      r:
        image: rocker/r-ver:4.1.2
        ports:
          - 6311:6311
        options: --name=r-service

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: Install R Dependencies
      run: |
        Rscript -e 'install.packages(c("R6"), repos=c("https://techtonique.r-universe.dev", "http://cran.rstudio.com/"))'
        Rscript -e 'install.packages(c("Rcpp"), repos=c("https://techtonique.r-universe.dev", "http://cran.rstudio.com/"))'
        Rscript -e 'install.packages(c("learningmachine"), repos=c("https://techtonique.r-universe.dev", "http://cran.rstudio.com/"))'

    - name: Run Python Examples from Subdirectory
      run: |
        find examples -maxdepth 2 -name "*.py" -exec  python {} \;

    - name: Cleanup
      run: |
        sudo killall -9 Rserve
