name: Python publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-run:
    runs-on: ubuntu-latest

    services:
      r:
        image: rocker/r-ver:4.1.2
        ports:
          - 6311:6311
        options: --name=r-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install R Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base
          sudo apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev  
          mkdir learningmachine_r
          Rscript -e "try(install.packages(c('R6', 'Rcpp', 'skimr'), lib='./learningmachine_r', dependencies=TRUE, repos='https://cloud.r-project.org'), silent=TRUE)"        
          Rscript -e "try(utils::install.packages('learningmachine', lib='./learningmachine_r', repos='https://techtonique.r-universe.dev', dependencies = TRUE), silent=TRUE)"

      - name: Install Python Dependencies
        run: |     
          python -m ensurepip --default-pip
          python -m pip install --upgrade pip       
          python -m pip list
          python -m pip install rpy2
          python -m pip install -r requirements.txt
          python -m pip install wheel
          python -m pip install .  --verbose

      - name: Debug Info
        run: |
          python --version
          python -m pip list
          python -m pip freeze
          Rscript --version
          ls -la 

      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
          ls -l dist

      - name: Run Python Examples from Subdirectory
        run: |
          find examples -maxdepth 2 -name "*.py" -exec  python {} \;

      #- name: Publish to PyPI                
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with: 
      #    password: ${{ secrets.PYPI_GLOBAL2 }}
      #    repository-url: https://upload.pypi.org/legacy/

  windows-run:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install RTools
        run: |
          $rtoolsVersion = "35"  # Adjust the version as needed
          $rtoolsUrl = "https://cran.r-project.org/bin/windows/Rtools/rtools$($rtoolsVersion)_x86_64.exe"
          $rtoolsInstallPath = "C:\RTools"
          
          # Download RTools installer
          Invoke-WebRequest -Uri $rtoolsUrl -OutFile "RTools.exe"
          
          # Install RTools
          Start-Process -Wait -FilePath "RTools.exe" -ArgumentList "/SILENT /DIR=$rtoolsInstallPath"
          
          # Add RTools to the system PATH
          $env:Path += ";$rtoolsInstallPath\bin;$rtoolsInstallPath\mingw64\bin"
          
          # Remove the downloaded installer
          Remove-Item "RTools.exe"
          
          Write-Host "RTools $rtoolsVersion installed successfully."
  
      - name: Show RTools Version
        run: rtools40version

      - name: Install R Dependencies
        run: |
          choco install r
          choco install openssl.light
          choco install curl
          mkdir learningmachine_r
          Rscript -e "try(install.packages(c('R6', 'Rcpp', 'skimr'), lib='./learningmachine_r', dependencies=TRUE, repos='https://cloud.r-project.org'), silent=TRUE)"        
          Rscript -e "try(utils::install.packages('learningmachine', lib='./learningmachine_r', repos='https://techtonique.r-universe.dev', dependencies = TRUE), silent=TRUE)"

      - name: Install Python Dependencies
        run: |     
          python -m pip install rpy2
          python -m pip install -r requirements.txt
          python -m pip install wheel
          python -m pip install .  --verbose

      - name: Debug Info
        run: |
          python --version
          python -m pip list
          python -m pip freeze
          Rscript --version
          ls -la 

      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
          ls -l dist

      - name: Run Python Examples from Subdirectory
        run: |
          Get-ChildItem -Recurse -Filter "*.py" | ForEach-Object { python $_.FullName }

      #- name: Publish to PyPI                
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with: 
      #    password: ${{ secrets.PYPI_GLOBAL2 }}
      #    repository-url: https://upload.pypi.org/legacy/

  macos-run:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install R Dependencies
        run: |
          brew install r
          brew install openssl
          brew install libxml2
          mkdir learningmachine_r
          Rscript -e "try(install.packages(c('R6', 'Rcpp', 'skimr'), lib='./learningmachine_r', dependencies=TRUE, repos='https://cloud.r-project.org'), silent=TRUE)"        
          Rscript -e "try(utils::install.packages('learningmachine', lib='./learningmachine_r', repos='https://techtonique.r-universe.dev', dependencies = TRUE), silent=TRUE)"

      - name: Install Python Dependencies
        run: |     
          python -m pip install rpy2
          python -m pip install -r requirements.txt
          python -m pip install wheel
          python -m pip install .  --verbose

      - name: Debug Info
        run: |
          python --version
          python -m pip list
          python -m pip freeze
          Rscript --version
          ls -la 

      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
          ls -l dist

      - name: Run Python Examples from Subdirectory
        run: |
          find examples -maxdepth 2 -name "*.py" -exec  python {} \;

      #- name: Publish to PyPI                
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with: 
      #    password: ${{ secrets.PYPI_GLOBAL2 }}
      #    repository-url: https://upload.pypi.org/legacy/
